title: VictLe66's Homepage
page-top-title: VictLe66
top-section-bg-text: Information Engineering
home-subtitle: VictLe66&ensp;|&ensp;韩信大王且66
copyright-text: '&copy; VictLe66 2023-2025. All Rights Reserved.'
